integrate TEP23_11_SCAFFOLDS.fasta
integrate Phaseolus.PaintedLady.CHROMOSOMES.fasta
integrate Phaseolus.DGD1962.CHROMOSOMES.fasta
integrate PI_311196_14_scaffolds.fasta
integrate phalu.B2C.gnm1.genome_main.fna
integrate phalu.G25393.gnm1.genome_main.fna
integrate Phaseolus.UC92.CHROMOSOMES.fasta
integrate Phaseolus.UC-Haskell.CHROMOSOMES.fasta
integrate Phaseolus.BAT93.CHROMOSOMES.fasta
integrate Phaseolus.Hystyle.CHROMOSOMES.fasta
integrate Phaseolus.Flavert.CHROMOSOMES.fasta
