integrate phaac.TEP23.protein.fasta
integrate phaco.PaintedLady.protein.fasta
integrate phade.DGD1962.protein.fasta
integrate phadu.PI_311196.protein.fasta
integrate phalu.B2C.protein.fasta
integrate phalu.G25393.protein.fasta
integrate phalu.UC92.protein.fasta
integrate phalu.UC-Haskell.protein.fasta
integrate phavu.BAT93.protein.fasta
integrate phavu.Hystyle.protein.fasta
integrate phavu.Flavert.protein.fasta
