integrate phaac.TEP23.transcript.fasta
integrate phaco.PaintedLady.transcript.fasta
integrate phade.DGD1962.transcript.fasta
integrate phadu.PI_311196.transcript.fasta
integrate phalu.B2C.transcript.fasta
integrate phalu.G25393.transcript.fasta
integrate phalu.UC92.transcript.fasta
integrate phalu.UC-Haskell.transcript.fasta
integrate phavu.BAT93.transcript.fasta
integrate phavu.Hystyle.transcript.fasta
integrate phavu.Flavert.transcript.fasta
