integrate phaac.TEP23.cds.fasta
integrate phaco.PaintedLady.cds.fasta
integrate phade.DGD1962.cds.fasta
integrate phadu.PI_311196.cds.fasta
integrate phalu.B2C.cds.fasta
integrate phalu.G25393.cds.fasta
integrate phalu.UC92.cds.fasta
integrate phalu.UC-Haskell.cds.fasta
integrate phavu.BAT93.cds.fasta
integrate phavu.Hystyle.cds.fasta
integrate phavu.Flavert.cds.fasta
